#!/bin/bash

echo "pwd"
echo `pwd`

echo "== Installing system packages =="
sudo apt-get update
sudo apt-get install -y libcurl4-openssl-dev
echo

git config --global user.name "gh_actions"
git config --global user.email "gh_actions@foreman_virt_who_configure.foreman"

echo "gemspec :path => '../foreman_virt_who_configure', :development_group => :dev" > bundler.d/foreman_virt_who_configure.local.rb
cp ../foreman_virt_who_configure/config/database.yml.example config/database.yml

rm -rf Gemfile.lock
bundle install --jobs=3 --retry=3 --without journald development console

export PGHOST=postgres
export PGUSER=foreman
export PGPASS=foreman
export RAILS_ENV=test
